<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{5ede9854-04af-4c4d-b59a-9eb30d0070e2}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Blowfish test
P_Blowfish();
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="101" Count="0" />
      <LineId Id="114" Count="0" />
      <LineId Id="30" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>